title: ioHubAccessDelayTest
code: ioHubDT
version: '0.5'
description: Example psychopy experiment running with ioHub (including pyEyeTrackerInterface) and ioDataStore.
total_sessions_to_run: 50
session_defaults:
    name: Session Name
    code: E1S01
    comments: None
    user_variables:
        participant_age: Unknown
        participant_gender: [ Select, Male, Female ]
        glasses: [Select, Yes, No ]
        contacts: [Select, Yes, No ]
        eye_color: Unknown
session_variable_order: [ name, code, comments, participant_age, participant_gender, glasses, contacts, eye_color ]
authors:
- name: Sol Simpson
  email: N/A
runtime: 
    script: run.py       # name of main script file for experiment (should contain the if __name__ is "__main__" : )
    name: psychopy              # name of experiment runtime environment used a.k.a psychopy
    api_version: 1.7.03         # minumum version of psychopy supported by experiment. (TO DO:  CURRENLY NOT CHECKED)
    python_version: 2.7         # minimum python version supported by experiment. (TO DO:  CURRENLY NOT CHECKED)
    python_exe: C:\python27\python.exe
event_buffer_length: 2048
ioHub:
    enable: True                # True = enable ioHub functionality
    config: ioHub_config.yaml   # specifies the config file to use for the ioHub, if enabled. File must be in experiment dir.
#
# Defines what Experiment Events can be sent from the experiment and stored to the ioHub file.
# See Experiment Event documentation for config param meanings. ( TO DO: NO DOCS YET )
# Currently Only 'Command' and "Message' are supported.  ** EXPERIMENT EVENTS ARE CURRENTLY BROKEN. **
#
events:
- event_class: MessageEvent
  prefix: 0
  msg_offset: 0
- event_class: CommandEvent
  priority: 0
  
